services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/chatdb'
  
  client:
    build: ./client
    ports:
      - "5000:5000"
    command: npm run dev

volumes:
  mongodb_data:
