services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/chatdb'
      SERVER_PORT: 3000
      CLIENT_URL: 'http://localhost:5000'
  
  client:
    build: ./client
    ports:
      - "5000:5000"
    environment:
      VITE_SERVER_URL: 'http://localhost:3000'

volumes:
  mongodb_data:
